name: Attach ZIP to Draft Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build ZIP
        run: |
          cd "${GITHUB_WORKSPACE}/custom_components/smart_offset_thermostat"
          zip -r "${GITHUB_WORKSPACE}/smart_offset_thermostat.zip" . \
            -x "**/__pycache__/*" \
            -x "**/*.pyc"

      - name: Upload ZIP to release (draft)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/smart_offset_thermostat.zip
          asset_name: smart_offset_thermostat.zip
          tag: ${{ github.event.release.tag_name }}
          overwrite: true
